version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.42.0
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup install nightly
            rustup component add rustfmt clippy
      - run:
          name: cargo check
          command: |
            cargo --version --verbose
            cargo check
      - run:
          name: cargo clippy
          # FIXME remove "allow" after this issue is fixed: https://git.io/Je07b
          command: |
            cargo clippy -- --allow clippy::needless_lifetimes
      - run:
          name: cargo fmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: cargo test
          command: |
            cargo test
      - run:
          name: "Check 'no std' build"
          command: |
            cargo +nightly --version --verbose
            cargo +nightly check --no-default-features
  fuzz:
    docker:
      - image: circleci/rust:1.42.0
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup install nightly
            cargo +nightly install --force cargo-fuzz
      - run:
          name: "Call the fuzz"
          command: |
            cargo +nightly fuzz run contract_v0_fuzz -- -runs=100000
workflows:
  version: 2
  run-build:
    jobs:
      - build
      - fuzz
