version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.38.0
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup install nightly
            rustup default nightly
            rustup component add rustfmt
            rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      - run:
          name: cargo check
          command: |
            cargo --version --verbose
            cargo check
      - run:
          name: cargo clippy
          # FIXME remove "allow" after this issue is fixed: https://git.io/Je07b
          command: |
            cargo clippy -- --allow clippy::needless_lifetimes
      - run:
          name: cargo fmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: cargo test
          command: |
            cargo test
      - run:
          name: "Check 'no std' build"
          command: |
            cargo --version --verbose
            cargo check --no-default-features
workflows:
  version: 2
  run-build:
    jobs:
      - build
